services:
  frontend:
    image: nginx:latest
    networks:
      - front-net

  backend:
    image: ubuntu:latest
    command: tail -f /dev/null
    networks:
      - front-net
      - data-net

  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=test
    networks:
      - data-net

networks:
  front-net:
  data-net:
