upstream web_load_balancer {
    server web1:80;
    server web2:8000;
}

server {
    listen 80;

    location /api/ {
        proxy_pass http://web_load_balancer/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-addr $remote_addr;
    }
}