upstream backend {
    ip_hash;

    server web1:80;
    server web2:80;
    server web3:80;
    server web4:80;
}

server {
    listen 80;

    location /api/v1/ {
        proxy_pass http://backend/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}